// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: Raquis/raquis.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RaquisService_RecibirNotificacion_FullMethodName = "/raquis.RaquisService/RecibirNotificacion"
)

// RaquisServiceClient is the client API for RaquisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RaquisServiceClient interface {
	RecibirNotificacion(ctx context.Context, in *Pedido, opts ...grpc.CallOption) (*Respuesta, error)
}

type raquisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRaquisServiceClient(cc grpc.ClientConnInterface) RaquisServiceClient {
	return &raquisServiceClient{cc}
}

func (c *raquisServiceClient) RecibirNotificacion(ctx context.Context, in *Pedido, opts ...grpc.CallOption) (*Respuesta, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Respuesta)
	err := c.cc.Invoke(ctx, RaquisService_RecibirNotificacion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RaquisServiceServer is the server API for RaquisService service.
// All implementations must embed UnimplementedRaquisServiceServer
// for forward compatibility.
type RaquisServiceServer interface {
	RecibirNotificacion(context.Context, *Pedido) (*Respuesta, error)
	mustEmbedUnimplementedRaquisServiceServer()
}

// UnimplementedRaquisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRaquisServiceServer struct{}

func (UnimplementedRaquisServiceServer) RecibirNotificacion(context.Context, *Pedido) (*Respuesta, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecibirNotificacion not implemented")
}
func (UnimplementedRaquisServiceServer) mustEmbedUnimplementedRaquisServiceServer() {}
func (UnimplementedRaquisServiceServer) testEmbeddedByValue()                       {}

// UnsafeRaquisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RaquisServiceServer will
// result in compilation errors.
type UnsafeRaquisServiceServer interface {
	mustEmbedUnimplementedRaquisServiceServer()
}

func RegisterRaquisServiceServer(s grpc.ServiceRegistrar, srv RaquisServiceServer) {
	// If the following call pancis, it indicates UnimplementedRaquisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RaquisService_ServiceDesc, srv)
}

func _RaquisService_RecibirNotificacion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pedido)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaquisServiceServer).RecibirNotificacion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RaquisService_RecibirNotificacion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaquisServiceServer).RecibirNotificacion(ctx, req.(*Pedido))
	}
	return interceptor(ctx, in, info, handler)
}

// RaquisService_ServiceDesc is the grpc.ServiceDesc for RaquisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RaquisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raquis.RaquisService",
	HandlerType: (*RaquisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecibirNotificacion",
			Handler:    _RaquisService_RecibirNotificacion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Raquis/raquis.proto",
}
