// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: Caravanas/caravanas.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tipo        string `protobuf:"bytes,2,opt,name=tipo,proto3" json:"tipo,omitempty"`
	Nombre      string `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Valor       int32  `protobuf:"varint,4,opt,name=valor,proto3" json:"valor,omitempty"`
	Escolta     string `protobuf:"bytes,5,opt,name=escolta,proto3" json:"escolta,omitempty"`
	Destino     string `protobuf:"bytes,6,opt,name=destino,proto3" json:"destino,omitempty"`
	Seguimiento int32  `protobuf:"varint,7,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
}

func (x *Pedido) Reset() {
	*x = Pedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Caravanas_caravanas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pedido) ProtoMessage() {}

func (x *Pedido) ProtoReflect() protoreflect.Message {
	mi := &file_Caravanas_caravanas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pedido.ProtoReflect.Descriptor instead.
func (*Pedido) Descriptor() ([]byte, []int) {
	return file_Caravanas_caravanas_proto_rawDescGZIP(), []int{0}
}

func (x *Pedido) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pedido) GetTipo() string {
	if x != nil {
		return x.Tipo
	}
	return ""
}

func (x *Pedido) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Pedido) GetValor() int32 {
	if x != nil {
		return x.Valor
	}
	return 0
}

func (x *Pedido) GetEscolta() string {
	if x != nil {
		return x.Escolta
	}
	return ""
}

func (x *Pedido) GetDestino() string {
	if x != nil {
		return x.Destino
	}
	return ""
}

func (x *Pedido) GetSeguimiento() int32 {
	if x != nil {
		return x.Seguimiento
	}
	return 0
}

type Estado struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seguimiento int32 `protobuf:"varint,1,opt,name=seguimiento,proto3" json:"seguimiento,omitempty"`
}

func (x *Estado) Reset() {
	*x = Estado{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Caravanas_caravanas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Estado) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Estado) ProtoMessage() {}

func (x *Estado) ProtoReflect() protoreflect.Message {
	mi := &file_Caravanas_caravanas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Estado.ProtoReflect.Descriptor instead.
func (*Estado) Descriptor() ([]byte, []int) {
	return file_Caravanas_caravanas_proto_rawDescGZIP(), []int{1}
}

func (x *Estado) GetSeguimiento() int32 {
	if x != nil {
		return x.Seguimiento
	}
	return 0
}

var File_Caravanas_caravanas_proto protoreflect.FileDescriptor

var file_Caravanas_caravanas_proto_rawDesc = []byte{
	0x0a, 0x19, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x73, 0x2f, 0x63, 0x61, 0x72, 0x61,
	0x76, 0x61, 0x6e, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x63, 0x61, 0x72,
	0x61, 0x76, 0x61, 0x6e, 0x61, 0x73, 0x22, 0xb0, 0x01, 0x0a, 0x06, 0x50, 0x65, 0x64, 0x69, 0x64,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x70, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x69, 0x70, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x6d, 0x62, 0x72, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x73, 0x63, 0x6f, 0x6c, 0x74, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x73, 0x63, 0x6f, 0x6c, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69,
	0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65,
	0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x06, 0x45, 0x73, 0x74,
	0x61, 0x64, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d, 0x69, 0x65, 0x6e,
	0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x73, 0x65, 0x67, 0x75, 0x69, 0x6d,
	0x69, 0x65, 0x6e, 0x74, 0x6f, 0x32, 0x4c, 0x0a, 0x10, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e,
	0x61, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x11, 0x2e, 0x63, 0x61,
	0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x73, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x1a, 0x11,
	0x2e, 0x63, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x73, 0x2e, 0x45, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x43, 0x61, 0x72, 0x61, 0x76, 0x61, 0x6e, 0x61, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Caravanas_caravanas_proto_rawDescOnce sync.Once
	file_Caravanas_caravanas_proto_rawDescData = file_Caravanas_caravanas_proto_rawDesc
)

func file_Caravanas_caravanas_proto_rawDescGZIP() []byte {
	file_Caravanas_caravanas_proto_rawDescOnce.Do(func() {
		file_Caravanas_caravanas_proto_rawDescData = protoimpl.X.CompressGZIP(file_Caravanas_caravanas_proto_rawDescData)
	})
	return file_Caravanas_caravanas_proto_rawDescData
}

var file_Caravanas_caravanas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_Caravanas_caravanas_proto_goTypes = []any{
	(*Pedido)(nil), // 0: caravanas.Pedido
	(*Estado)(nil), // 1: caravanas.Estado
}
var file_Caravanas_caravanas_proto_depIdxs = []int32{
	0, // 0: caravanas.CaravanasService.ProcesarPedido:input_type -> caravanas.Pedido
	1, // 1: caravanas.CaravanasService.ProcesarPedido:output_type -> caravanas.Estado
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_Caravanas_caravanas_proto_init() }
func file_Caravanas_caravanas_proto_init() {
	if File_Caravanas_caravanas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Caravanas_caravanas_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Pedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_Caravanas_caravanas_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Estado); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Caravanas_caravanas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_Caravanas_caravanas_proto_goTypes,
		DependencyIndexes: file_Caravanas_caravanas_proto_depIdxs,
		MessageInfos:      file_Caravanas_caravanas_proto_msgTypes,
	}.Build()
	File_Caravanas_caravanas_proto = out.File
	file_Caravanas_caravanas_proto_rawDesc = nil
	file_Caravanas_caravanas_proto_goTypes = nil
	file_Caravanas_caravanas_proto_depIdxs = nil
}
