// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: Caravanas/caravanas.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CaravanasService_ProcesarPedido_FullMethodName = "/caravanas.CaravanasService/ProcesarPedido"
)

// CaravanasServiceClient is the client API for CaravanasService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CaravanasServiceClient interface {
	ProcesarPedido(ctx context.Context, in *Pedido, opts ...grpc.CallOption) (*Estado, error)
}

type caravanasServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCaravanasServiceClient(cc grpc.ClientConnInterface) CaravanasServiceClient {
	return &caravanasServiceClient{cc}
}

func (c *caravanasServiceClient) ProcesarPedido(ctx context.Context, in *Pedido, opts ...grpc.CallOption) (*Estado, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Estado)
	err := c.cc.Invoke(ctx, CaravanasService_ProcesarPedido_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CaravanasServiceServer is the server API for CaravanasService service.
// All implementations must embed UnimplementedCaravanasServiceServer
// for forward compatibility.
type CaravanasServiceServer interface {
	ProcesarPedido(context.Context, *Pedido) (*Estado, error)
	mustEmbedUnimplementedCaravanasServiceServer()
}

// UnimplementedCaravanasServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCaravanasServiceServer struct{}

func (UnimplementedCaravanasServiceServer) ProcesarPedido(context.Context, *Pedido) (*Estado, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcesarPedido not implemented")
}
func (UnimplementedCaravanasServiceServer) mustEmbedUnimplementedCaravanasServiceServer() {}
func (UnimplementedCaravanasServiceServer) testEmbeddedByValue()                          {}

// UnsafeCaravanasServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CaravanasServiceServer will
// result in compilation errors.
type UnsafeCaravanasServiceServer interface {
	mustEmbedUnimplementedCaravanasServiceServer()
}

func RegisterCaravanasServiceServer(s grpc.ServiceRegistrar, srv CaravanasServiceServer) {
	// If the following call pancis, it indicates UnimplementedCaravanasServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CaravanasService_ServiceDesc, srv)
}

func _CaravanasService_ProcesarPedido_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pedido)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CaravanasServiceServer).ProcesarPedido(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CaravanasService_ProcesarPedido_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CaravanasServiceServer).ProcesarPedido(ctx, req.(*Pedido))
	}
	return interceptor(ctx, in, info, handler)
}

// CaravanasService_ServiceDesc is the grpc.ServiceDesc for CaravanasService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CaravanasService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "caravanas.CaravanasService",
	HandlerType: (*CaravanasServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcesarPedido",
			Handler:    _CaravanasService_ProcesarPedido_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Caravanas/caravanas.proto",
}
