// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SupervisorServiceClient is the client API for SupervisorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupervisorServiceClient interface {
	SendCommandToBroker(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	HandleResponse(ctx context.Context, in *Response, opts ...grpc.CallOption) (*empty.Empty, error)
}

type supervisorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupervisorServiceClient(cc grpc.ClientConnInterface) SupervisorServiceClient {
	return &supervisorServiceClient{cc}
}

func (c *supervisorServiceClient) SendCommandToBroker(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/supervisoreshexgate.SupervisorService/SendCommandToBroker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supervisorServiceClient) HandleResponse(ctx context.Context, in *Response, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/supervisoreshexgate.SupervisorService/HandleResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupervisorServiceServer is the server API for SupervisorService service.
// All implementations must embed UnimplementedSupervisorServiceServer
// for forward compatibility
type SupervisorServiceServer interface {
	SendCommandToBroker(context.Context, *Request) (*Response, error)
	HandleResponse(context.Context, *Response) (*empty.Empty, error)
	mustEmbedUnimplementedSupervisorServiceServer()
}

// UnimplementedSupervisorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSupervisorServiceServer struct {
}

func (UnimplementedSupervisorServiceServer) SendCommandToBroker(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommandToBroker not implemented")
}
func (UnimplementedSupervisorServiceServer) HandleResponse(context.Context, *Response) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleResponse not implemented")
}
func (UnimplementedSupervisorServiceServer) mustEmbedUnimplementedSupervisorServiceServer() {}

// UnsafeSupervisorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupervisorServiceServer will
// result in compilation errors.
type UnsafeSupervisorServiceServer interface {
	mustEmbedUnimplementedSupervisorServiceServer()
}

func RegisterSupervisorServiceServer(s grpc.ServiceRegistrar, srv SupervisorServiceServer) {
	s.RegisterService(&SupervisorService_ServiceDesc, srv)
}

func _SupervisorService_SendCommandToBroker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).SendCommandToBroker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisoreshexgate.SupervisorService/SendCommandToBroker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).SendCommandToBroker(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupervisorService_HandleResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Response)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupervisorServiceServer).HandleResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisoreshexgate.SupervisorService/HandleResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupervisorServiceServer).HandleResponse(ctx, req.(*Response))
	}
	return interceptor(ctx, in, info, handler)
}

// SupervisorService_ServiceDesc is the grpc.ServiceDesc for SupervisorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupervisorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "supervisoreshexgate.SupervisorService",
	HandlerType: (*SupervisorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommandToBroker",
			Handler:    _SupervisorService_SendCommandToBroker_Handler,
		},
		{
			MethodName: "HandleResponse",
			Handler:    _SupervisorService_HandleResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supervisoreshexgate.proto",
}

// BrokerServiceClient is the client API for BrokerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BrokerServiceClient interface {
	RedirectRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type brokerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBrokerServiceClient(cc grpc.ClientConnInterface) BrokerServiceClient {
	return &brokerServiceClient{cc}
}

func (c *brokerServiceClient) RedirectRequest(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/supervisoreshexgate.BrokerService/RedirectRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BrokerServiceServer is the server API for BrokerService service.
// All implementations must embed UnimplementedBrokerServiceServer
// for forward compatibility
type BrokerServiceServer interface {
	RedirectRequest(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedBrokerServiceServer()
}

// UnimplementedBrokerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBrokerServiceServer struct {
}

func (UnimplementedBrokerServiceServer) RedirectRequest(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedirectRequest not implemented")
}
func (UnimplementedBrokerServiceServer) mustEmbedUnimplementedBrokerServiceServer() {}

// UnsafeBrokerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BrokerServiceServer will
// result in compilation errors.
type UnsafeBrokerServiceServer interface {
	mustEmbedUnimplementedBrokerServiceServer()
}

func RegisterBrokerServiceServer(s grpc.ServiceRegistrar, srv BrokerServiceServer) {
	s.RegisterService(&BrokerService_ServiceDesc, srv)
}

func _BrokerService_RedirectRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BrokerServiceServer).RedirectRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisoreshexgate.BrokerService/RedirectRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BrokerServiceServer).RedirectRequest(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// BrokerService_ServiceDesc is the grpc.ServiceDesc for BrokerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BrokerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "supervisoreshexgate.BrokerService",
	HandlerType: (*BrokerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RedirectRequest",
			Handler:    _BrokerService_RedirectRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supervisoreshexgate.proto",
}
